from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


@dataclass(frozen=True)
class ScreenState:
    """Normalized screen observation; raw pixels are optional and never persisted by default."""

    source: str
    width: int
    height: int
    elements: list[dict[str, Any]]


class ScreenAdapter(Protocol):
    async def observe(self) -> ScreenState: ...
    async def click(self, x: int, y: int) -> dict[str, Any]: ...
    async def type_text(self, text: str) -> dict[str, Any]: ...
    async def scroll(self, delta: int) -> dict[str, Any]: ...
    async def press_back(self) -> dict[str, Any]: ...


class NotificationAdapter(Protocol):
    async def subscribe(self) -> Any: ...


class MessagingAdapter(Protocol):
    async def send(self, recipient: str, text: str) -> dict[str, Any]: ...


class BrowserAdapter(Protocol):
    async def open(self, url: str) -> dict[str, Any]: ...
    async def observe(self) -> ScreenState: ...
    async def click(self, x: int, y: int) -> dict[str, Any]: ...
    async def type_text(self, text: str) -> dict[str, Any]: ...
    async def navigate(self, url: str) -> dict[str, Any]: ...
