from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from .models import Plan, Risk, ToolCall


class Planner(Protocol):
    async def plan(self, goal: str, context: dict[str, Any]) -> Plan: ...


@dataclass(frozen=True)
class RulePlanner:
    """Deterministic fallback planner. Model adapters can replace this without changing runtime."""

    async def plan(self, goal: str, context: dict[str, Any]) -> Plan:
        text = goal.lower()
        steps: list[ToolCall] = []
        if any(word in text for word in ("search", "find", "look up", "check")):
            steps.append(ToolCall(name="web.search", arguments={"query": goal}, risk=Risk.READ))
        if any(word in text for word in ("send", "post", "message", "email")):
            steps.append(ToolCall(name="communications.send", arguments={"text": goal}, risk=Risk.HIGH))
        if any(word in text for word in ("buy", "purchase", "order", "pay")):
            steps.append(ToolCall(name="commerce.purchase", arguments={"request": goal}, risk=Risk.CRITICAL))
        return Plan(goal=goal, steps=steps, explanation="Generated by the provider-neutral fallback planner.")
