from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Protocol

from .models import Plan, Risk, ToolCall


class Planner(Protocol):
    async def plan(self, goal: str, context: dict[str, Any]) -> Plan: ...


@dataclass(frozen=True)
class RulePlanner:
    """Deterministic fallback planner with real-device actions when a device is connected."""

    async def plan(self, goal: str, context: dict[str, Any]) -> Plan:
        text = goal.lower()
        device_id = str(context.get("device_id", "")).strip()
        steps: list[ToolCall] = []

        if device_id and any(word in text for word in ("search", "find", "look up", "google", "check")):
            steps.append(ToolCall(name="device_search_google", arguments={"query": goal}, risk=Risk.LOW))
        elif any(word in text for word in ("search", "find", "look up", "check")):
            steps.append(ToolCall(name="web.search", arguments={"query": goal}, risk=Risk.READ))

        if device_id and ("http://" in text or "https://" in text or "open website" in text or "open site" in text):
            url = next((part for part in goal.split() if part.startswith(("http://", "https://"))), "")
            if url:
                steps.append(ToolCall(name="device_open_url", arguments={"url": url}, risk=Risk.LOW))

        if device_id and any(word in text for word in ("back", "go back")):
            steps.append(ToolCall(name="device_back", arguments={}, risk=Risk.LOW))

        if device_id and "map" in text and any(word in text for word in ("search", "find", "show")):
            steps.append(ToolCall(name="device_maps_search", arguments={"query": goal}, risk=Risk.LOW))

        if any(word in text for word in ("send", "post", "message", "email")):
            if device_id and "email" in text:
                steps.append(ToolCall(name="device_compose_email", arguments={"text": goal}, risk=Risk.HIGH))
            else:
                steps.append(ToolCall(name="communications.send", arguments={"text": goal}, risk=Risk.HIGH))

        if any(word in text for word in ("buy", "purchase", "order", "pay", "payment")):
            if device_id and "upi" in text:
                steps.append(ToolCall(name="device_upi_payment", arguments={"intent_uri": context.get("upi_intent_uri", "")}, risk=Risk.CRITICAL))
            else:
                steps.append(ToolCall(name="commerce.purchase", arguments={"request": goal}, risk=Risk.CRITICAL))
        return Plan(goal=goal, steps=steps, explanation="Generated by the deterministic fallback planner.")


@dataclass
class ModelPlanner:
    """Research-informed closed-loop planner for real GUI, browser and device execution."""

    llm: Any
    fallback: Planner

    async def plan(self, goal: str, context: dict[str, Any]) -> Plan:
        tools = context.get("available_tools", [])
        memory = context.get("memory", [])[-12:]
        messages = [
            {
                "role": "system",
                "content": (
                    "You are TOM's planning engine. Return ONLY valid JSON matching "
                    '{"goal": string, "steps": [{"name": string, "arguments": object, "risk": "read|low|high|critical"}], '
                    '"explanation": string, "needs_clarification": boolean, "clarification_question": string}. '
                    "Use only tools listed in available_tools. Never invent a tool. "
                    "If a consequential request is ambiguous in a way that changes the target, channel, recipient, amount, account or final outcome, ask one concise clarification question instead of guessing. "
                    "Example: 'message Muskan' when both WhatsApp and Instagram are plausible -> ask 'WhatsApp or Instagram?'. "
                    "Do not ask unnecessary questions when the intended action is already clear. "
                    "For GUI work use a closed loop: observe current state -> choose the smallest grounded action -> execute -> verify with a fresh observation -> re-ground before continuing. "
                    "Fuse accessibility/semantic UI metadata with screenshots when both exist; use screenshots as visual truth for layout, transient overlays and custom-rendered controls. "
                    "For dense or uncertain targets prefer a narrow search/refinement step over a blind coordinate click. "
                    "Prefer semantic targets over coordinates, but fall back to coordinates when semantic metadata is absent. "
                    "Use batch actions only for low-risk, reversible sequences whose preconditions are stable; never batch consequential actions. "
                    "When an action fails or the screen changes unexpectedly, re-plan from the new observation rather than repeating the same action blindly. "
                    "For real-world tasks combine GUI actions with available typed/API/CLI tools when they provide a more reliable path, then verify the resulting external state. "
                    "For long tasks preserve constraints, important state and user intent in memory; do not assume hidden state. "
                    "Sending messages, purchases, deletion, account/security changes are high or critical and require approval policy. "
                    "Do not claim completion; only create the plan."
                ),
            },
            {
                "role": "user",
                "content": json.dumps(
                    {"goal": goal, "available_tools": tools, "recent_memory": memory, "context": context},
                    ensure_ascii=False,
                ),
            },
        ]
        try:
            raw = await self.llm.complete(messages, temperature=0, response_format={"type": "json_object"})
            return self._parse(raw, goal, tools)
        except Exception:  # noqa: BLE001 - model providers are external boundaries
            return await self.fallback.plan(goal, context)

    @staticmethod
    def _parse(raw: str, goal: str, tools: list[dict[str, Any]]) -> Plan:
        text = raw.strip()
        if text.startswith("```"):
            text = text.strip("`").replace("json\n", "", 1).strip()
        payload = json.loads(text)
        plan = Plan.model_validate(payload)
        allowed = {item.get("name") for item in tools}
        if any(step.name not in allowed for step in plan.steps):
            raise ValueError("model returned an unavailable tool")
        tool_risks = {item.get("name"): item.get("risk") for item in tools}
        for step in plan.steps:
            declared = tool_risks.get(step.name)
            if declared and step.risk.value != declared:
                raise ValueError(f"model risk mismatch for tool: {step.name}")
        if plan.needs_clarification and plan.steps:
            raise ValueError("clarification plan must not contain executable steps")
        return plan.model_copy(update={"goal": goal})
